// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsm4I_fcfziH76-NNtDQImfSUonx6qut0',
    appId: '1:133507150925:web:dc5a1152b21483c620d804',
    messagingSenderId: '133507150925',
    projectId: 'fourcoop-19d08',
    authDomain: 'fourcoop-19d08.firebaseapp.com',
    storageBucket: 'fourcoop-19d08.firebasestorage.app',
    measurementId: 'G-7J23TY5E53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuEHtzl5W-k4fYMX1XDvSPoEAUO5cuHmw',
    appId: '1:133507150925:android:c6afbe19485ab9bc20d804',
    messagingSenderId: '133507150925',
    projectId: 'fourcoop-19d08',
    storageBucket: 'fourcoop-19d08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ZUQwsj0CAxTqWVToiR94giOV6if1VTE',
    appId: '1:133507150925:ios:fc3eb407d0c9b2aa20d804',
    messagingSenderId: '133507150925',
    projectId: 'fourcoop-19d08',
    storageBucket: 'fourcoop-19d08.firebasestorage.app',
    iosBundleId: 'com.domain.fourcoop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ZUQwsj0CAxTqWVToiR94giOV6if1VTE',
    appId: '1:133507150925:ios:fc3eb407d0c9b2aa20d804',
    messagingSenderId: '133507150925',
    projectId: 'fourcoop-19d08',
    storageBucket: 'fourcoop-19d08.firebasestorage.app',
    iosBundleId: 'com.domain.fourcoop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsm4I_fcfziH76-NNtDQImfSUonx6qut0',
    appId: '1:133507150925:web:cf4ab63e9a1924e820d804',
    messagingSenderId: '133507150925',
    projectId: 'fourcoop-19d08',
    authDomain: 'fourcoop-19d08.firebaseapp.com',
    storageBucket: 'fourcoop-19d08.firebasestorage.app',
    measurementId: 'G-E9WTTJC66F',
  );
}
